# Generated by Django 5.0.14 on 2026-08-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_ciphertext', models.TextField()),
                ('body_nonce', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('flagged', 'Flagged')], default='active', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
