# Generated by Django 5.0.14 on 2026-08-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name_ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name_nonce',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
