# Generated by Django 5.0.14 on 2026-08-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0006_message_sender_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_ciphertext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_nonce',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
