# Generated by Django 5.0.14 on 2026-08-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0007_message_replied_at_message_reply_ciphertext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply_ciphertext',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
