# Generated by Django 5.0.14 on 2026-10-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0008_alter_message_reply_ciphertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
