# Generated by Django 5.0.14 on 2026-08-28 05:34

from django.db import migrations, models


def enable_notify_for_existing(apps, schema_editor):
    UserSettings = apps.get_model("users", "UserSettings")
    UserSettings.objects.all().update(notify_new_message=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='notify_new_message',
            field=models.BooleanField(default=True),
        ),
        # Existing accounts keep the new default too: alerts were OFF by
        # default before, so turn them ON for every current user.
        migrations.RunPython(enable_notify_for_existing, migrations.RunPython.noop),
    ]
